// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FullapplictaionTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void fullapplictaionTest() {
    driver.get("http://localhost:5173/");
    driver.manage().window().setSize(new Dimension(1054, 898));
    driver.findElement(By.cssSelector("div:nth-child(1) > .border")).click();
    driver.findElement(By.cssSelector("div:nth-child(1) > .border")).click();
    driver.findElement(By.cssSelector("div:nth-child(1) > .border")).sendKeys("joel");
    driver.findElement(By.cssSelector(".lucide")).click();
    driver.findElement(By.cssSelector(".pr-10")).click();
    driver.findElement(By.cssSelector(".pr-10")).sendKeys("joel1234");
    driver.findElement(By.cssSelector(".shadow-md")).click();
    driver.findElement(By.cssSelector(".hover\\3Aopacity-90")).click();
    driver.findElement(By.cssSelector(".rounded-xl:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".rounded-xl:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".p-6:nth-child(1) > .w-full")).click();
    driver.findElement(By.cssSelector(".space-y-4 > .w-full:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".space-y-4 > .w-full:nth-child(1)")).sendKeys("joel");
    driver.findElement(By.cssSelector(".space-y-4 > .w-full:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".space-y-4 > .w-full:nth-child(2)")).sendKeys("7998845665");
    driver.findElement(By.cssSelector(".w-full:nth-child(3)")).sendKeys("5654856184848561");
    driver.findElement(By.cssSelector(".grid > .w-full:nth-child(1)")).sendKeys("02/12");
    driver.findElement(By.cssSelector(".grid > .w-full:nth-child(2)")).sendKeys("254");
    driver.findElement(By.cssSelector(".bg-red-500")).click();
    assertThat(driver.switchTo().alert().getText(), is("Payment successful and Plan Subscribed!"));
    driver.findElement(By.cssSelector(".bg-red-500")).click();
    driver.findElement(By.cssSelector(".p-6:nth-child(3) > .flex")).click();
    driver.findElement(By.cssSelector(".p-6:nth-child(2) .px-4")).click();
    driver.findElement(By.cssSelector(".space-y-4 > .w-full:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".space-y-4 > .w-full:nth-child(1)")).sendKeys("Jeol");
    driver.findElement(By.cssSelector(".w-full:nth-child(3)")).sendKeys("6565454464684684");
    driver.findElement(By.cssSelector(".grid > .w-full:nth-child(1)")).sendKeys("12/23");
    driver.findElement(By.cssSelector(".grid > .w-full:nth-child(2)")).sendKeys("151");
    driver.findElement(By.cssSelector(".bg-red-500")).click();
    assertThat(driver.switchTo().alert().getText(), is("Subscription renewed successfully!"));
    driver.findElement(By.cssSelector(".bg-red-500")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".bg-red-500"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Product")).click();
    {
      WebElement element = driver.findElement(By.linkText("Product"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".p-4:nth-child(1) .border")).click();
    driver.findElement(By.cssSelector(".p-4:nth-child(3) .border")).click();
    driver.findElement(By.cssSelector(".px-3")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".px-3"));
      dropdown.findElement(By.xpath("//option[. = 'Router']")).click();
    }
    driver.findElement(By.cssSelector(".px-3")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".px-3"));
      dropdown.findElement(By.xpath("//option[. = 'Tablet']")).click();
    }
    driver.findElement(By.cssSelector(".px-3")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".px-3"));
      dropdown.findElement(By.xpath("//option[. = 'All']")).click();
    }
    driver.findElement(By.cssSelector(".p-4:nth-child(2) .border")).click();
    driver.findElement(By.cssSelector(".text-white")).click();
    driver.findElement(By.cssSelector(".px-2:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".text-white")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".text-white"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".w-full:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".w-full:nth-child(1)")).sendKeys("Joel");
    driver.findElement(By.cssSelector(".w-full:nth-child(2)")).sendKeys("6841568486");
    driver.findElement(By.cssSelector(".w-full:nth-child(3)")).sendKeys("Bangalore KA");
    driver.findElement(By.cssSelector(".w-full:nth-child(4)")).sendKeys("6546168161861681");
    driver.findElement(By.cssSelector(".grid > .border:nth-child(1)")).sendKeys("12/23");
    driver.findElement(By.cssSelector(".grid > .border:nth-child(2)")).sendKeys("215");
    driver.findElement(By.cssSelector(".bg-red-500")).click();
    driver.findElement(By.cssSelector(".bg-red-500")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".bg-red-500"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".relative path:nth-child(1)")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".p-4:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".p-4:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".p-4:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".p-4:nth-child(1)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".p-4:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.linkText("Orders")).click();
    {
      WebElement element = driver.findElement(By.linkText("Orders"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".mt-6 > .px-6")).click();
    assertThat(driver.switchTo().alert().getText(), is("Order #10 has been cancelled successfully."));
    driver.findElement(By.cssSelector(".relative path:nth-child(1)")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".p-4:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".p-4:nth-child(1) > .text-gray-400")).click();
    driver.findElement(By.cssSelector(".p-4:nth-child(1) > .text-gray-400")).click();
    driver.findElement(By.cssSelector("path:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".text-gray-800")).click();
    driver.findElement(By.cssSelector(".text-white")).click();
    driver.findElement(By.name("lastName")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).click();
    {
      WebElement element = driver.findElement(By.name("email"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("email")).sendKeys("joel@gmail.com");
    driver.findElement(By.name("phone")).click();
    driver.findElement(By.name("phone")).click();
    {
      WebElement element = driver.findElement(By.name("phone"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("phone")).sendKeys("+919876544558");
    driver.findElement(By.cssSelector(".text-white:nth-child(1)")).click();
    assertThat(driver.switchTo().alert().getText(), is("User updated successfully!"));
    driver.findElement(By.cssSelector(".hover\\3A bg-gray-50")).click();
    driver.findElement(By.cssSelector(".hover\\3A bg-gray-50")).click();
    driver.findElement(By.cssSelector(".space-y-4 > div:nth-child(1) > .w-full")).click();
    driver.findElement(By.cssSelector(".space-y-4 > div:nth-child(1) > .w-full")).sendKeys("user");
    driver.findElement(By.cssSelector(".grid:nth-child(2) > div:nth-child(1) > .w-full")).sendKeys("user");
    driver.findElement(By.cssSelector("div:nth-child(3) > .w-full")).sendKeys("user@gmail.com");
    driver.findElement(By.cssSelector("div:nth-child(4) > .w-full")).sendKeys("1234689875");
    driver.findElement(By.cssSelector(".relative:nth-child(1) > .border")).sendKeys("user1234");
    driver.findElement(By.cssSelector(".relative:nth-child(1) path")).click();
    driver.findElement(By.cssSelector(".lucide-eye > path")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".lucide-eye > path"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".relative:nth-child(2) > .w-full")).click();
    driver.findElement(By.cssSelector(".relative:nth-child(2) > .w-full")).sendKeys("user1234");
    driver.findElement(By.cssSelector(".shadow-md")).click();
    assertThat(driver.switchTo().alert().getText(), is("Registration failed"));
    driver.findElement(By.cssSelector(".hover\\3A bg-gray-50")).click();
    driver.findElement(By.cssSelector("div:nth-child(1) > .border")).click();
    driver.findElement(By.cssSelector("div:nth-child(1) > .border")).sendKeys("joel");
    driver.findElement(By.cssSelector(".pr-10")).click();
    driver.findElement(By.cssSelector("div:nth-child(1) > .border")).sendKeys("joel");
    driver.findElement(By.cssSelector(".pr-10")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".shadow-md")).click();
  }
}
