--
-- PostgreSQL database dump
--

-- Dumped from database version 15.13
-- Dumped by pg_dump version 15.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admins (
    admin_id bigint NOT NULL,
    admin_email character varying(255) NOT NULL,
    admin_username character varying(255) NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    password character varying(255)
);


ALTER TABLE public.admins OWNER TO postgres;

--
-- Name: admins_admin_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.admins ALTER COLUMN admin_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admins_admin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    email character varying(255) NOT NULL,
    email_verified boolean,
    first_name character varying(255),
    last_name character varying(255),
    password character varying(255),
    phone character varying(255),
    username character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: admins; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.admins (admin_id, admin_email, admin_username, first_name, last_name, password) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (user_id, email, email_verified, first_name, last_name, password, phone, username) FROM stdin;
2	john@gmail.com	f	John		$2a$10$zc8tNp3htHB18nTzB2XmweeJbmXwy.SktLe4EmosCx8dWn3d15FAK	789799878	john
3	jerrin@gmail.com	f	Jerrin		$2a$10$wLNt/gRQW9yNxd/VWsJ2SOpevsY/e4u2I2OgfRijeY/tjgkt3QYN2	789987987	jerrin
5	user@gmail.com	f	user		$2a$10$lmetq..LKLGpTc77urTN1u9yN3apwkzIoAuGzMi3MmJ6QWS1G.EjK	7897897898	user
1	joel@gmail.com	f	Joel	Jino	$2a$10$gBTyYfrnJAqtybh14ouBoui9EhX79CQst7uFPZeg.LBrG4sGMw2DG	+919876544558	joel
11	brigit@gmail.com	f	Brigit		$2a$10$69jomlmpYaf3yUidnZt2Z.scOrY4zQDtEEmLbcJQShWO9LExQo4fG	8799879878	brigit
12	roshini@gmail.com	f	Roshini		$2a$10$UV0pi3cq5ro0Qn8mpbU//OgknBX1Bw4lzPJTNXcqHX7wpZBpbR9zq	8248849875	rosh
13	jeni@gmail.com	f	Jeni		$2a$10$kREcPJjsNIgqi1tDZCBX4..qOm3lc63y6fY14zIritYQqONtoRMnS	8248849275	jeni
\.


--
-- Name: admins_admin_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.admins_admin_id_seq', 1, false);


--
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_id_seq', 13, true);


--
-- Name: admins admins_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT admins_pkey PRIMARY KEY (admin_id);


--
-- Name: admins uk3qu9rv6p2v6qphyya19due8v9; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT uk3qu9rv6p2v6qphyya19due8v9 UNIQUE (admin_username);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: admins ukeoomxwhv11jtwt1lqr3h1nf4h; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT ukeoomxwhv11jtwt1lqr3h1nf4h UNIQUE (admin_email);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- PostgreSQL database dump complete
--

