--
-- PostgreSQL database dump
--

-- Dumped from database version 15.13
-- Dumped by pg_dump version 15.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    product_id bigint NOT NULL,
    base_price numeric(38,2),
    category character varying(255),
    created_at timestamp(6) without time zone,
    image_url character varying(255),
    is_active boolean NOT NULL,
    product_description text,
    product_name character varying(255),
    specifications text,
    stock_quantity integer,
    updated_at timestamp(6) without time zone
);


ALTER TABLE public.products OWNER TO postgres;

--
-- Name: products_product_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products ALTER COLUMN product_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vas_catalog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vas_catalog (
    service_id bigint NOT NULL,
    billing_cycle character varying(255),
    created_at timestamp(6) without time zone,
    features text,
    is_active boolean NOT NULL,
    price numeric(38,2),
    service_description text,
    service_name character varying(255),
    service_type character varying(255),
    updated_at timestamp(6) without time zone,
    CONSTRAINT vas_catalog_billing_cycle_check CHECK (((billing_cycle)::text = ANY ((ARRAY['MONTHLY'::character varying, 'QUARTERLY'::character varying, 'YEARLY'::character varying])::text[])))
);


ALTER TABLE public.vas_catalog OWNER TO postgres;

--
-- Name: vas_catalog_service_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.vas_catalog ALTER COLUMN service_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vas_catalog_service_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products (product_id, base_price, category, created_at, image_url, is_active, product_description, product_name, specifications, stock_quantity, updated_at) FROM stdin;
1	1499.00	Router	2025-09-01 11:41:51.571792	https://raw.githubusercontent.com/angeline-31/images/362b160ff70a191e60d303639bb261373a820354/router1.png	t	High-speed dual band WiFi router with 100 Mbps support and strong coverage.	WiFi Router X100	{\n    "WiFi Standard": "802.11ac",\n    "Frequency Bands": "2.4GHz and 5GHz",\n    "Maximum Speed": "100 Mbps",\n    "Ethernet Ports": "4 LAN + 1 WAN",\n    "Antenna Type": "2 external high-gain antennas",\n    "Security": "WPA2/WPA3 encryption, Firewall",\n    "Dimensions": "200 x 150 x 30 mm",\n    "Power Supply": "12V DC, 1A"\n  }	100	2025-09-01 11:41:51.571792
2	2499.00	Router	2025-09-01 11:43:39.289006	https://raw.githubusercontent.com/angeline-31/images/362b160ff70a191e60d303639bb261373a820354/router2.png	t	Next-gen 5G enabled router for seamless connectivity and faster speeds.	WiFi Router Pro 5G	{\n    "WiFi Standard": "802.11ax (WiFi 6)",\n    "Frequency Bands": "2.4GHz and 5GHz dual-band",\n    "Maximum Speed": "1.2 Gbps",\n    "5G Support": "Integrated SIM slot with 5G NR support",\n    "Ethernet Ports": "4 Gigabit LAN + 1 Gigabit WAN",\n    "Antenna Type": "4 high-gain external antennas",\n    "Security": "WPA3 encryption, DoS protection, Firewall",\n    "Dimensions": "220 x 160 x 35 mm",\n    "Power Supply": "12V DC, 2A"\n  }	100	2025-09-01 11:43:39.289006
3	8999.00	Tablet	2025-09-01 11:43:52.033504	https://raw.githubusercontent.com/angeline-31/images/362b160ff70a191e60d303639bb261373a820354/tablet1.png	t	10-inch HD display Android tablet perfect for work, study, and entertainment.	Android Tablet 10"	{\n    "Display": "10.1-inch HD IPS, 1280x800 resolution",\n    "Processor": "Octa-core 2.0 GHz",\n    "RAM": "4 GB",\n    "Storage": "64 GB internal, expandable up to 512 GB via microSD",\n    "Operating System": "Android 13",\n    "Battery": "7000 mAh, up to 12 hours usage",\n    "Connectivity": "Wi-Fi 802.11ac, Bluetooth 5.0, USB-C",\n    "Camera": "8 MP rear, 5 MP front",\n    "Audio": "Dual stereo speakers",\n    "Dimensions": "245 x 160 x 8 mm",\n    "Weight": "480 g"\n  }	100	2025-09-01 11:43:52.033504
4	4999.00	Tablet	2025-09-01 11:44:02.670745	https://raw.githubusercontent.com/angeline-31/images/362b160ff70a191e60d303639bb261373a820354/tablet2.png	t	Durable kids learning tablet with parental control and preloaded apps.	Kids Learning Tablet	{\n    "Display": "7-inch HD touch screen",\n    "Processor": "Quad-core 1.3 GHz",\n    "RAM": "2 GB",\n    "Storage": "32 GB (expandable up to 128 GB via microSD)",\n    "Battery": "3500 mAh (up to 6 hours use)",\n    "OS": "Android 11 (Kids Mode)",\n    "Connectivity": "Wi-Fi, Bluetooth 4.2",\n    "Parental Control": "Built-in app and screen time management",\n    "Preloaded Apps": "Educational games, e-books, drawing tools",\n    "Weight": "300 g",\n    "Color": "Blue with rugged protective case"\n  }	100	2025-09-01 11:44:02.670745
5	1999.00	Bluetooth	2025-09-01 11:44:14.824255	https://raw.githubusercontent.com/angeline-31/images/362b160ff70a191e60d303639bb261373a820354/bluetooth1.png	t	Wireless Bluetooth headset with noise cancellation and long battery life.	Bluetooth Headset	{\n    "Bluetooth Version": "5.0",\n    "Driver Size": "40 mm",\n    "Noise Cancellation": "Active Noise Cancellation (ANC)",\n    "Battery Life": "20 hours playback, 2 hours charging time",\n    "Charging Port": "USB Type-C",\n    "Microphone": "Built-in with ENC for calls",\n    "Frequency Response": "20 Hz - 20 kHz",\n    "Weight": "180 g",\n    "Color": "Black",\n    "Wireless Range": "10 meters",\n    "Controls": "Touch controls for volume, track, and calls",\n    "Foldable Design": "Yes, for easy storage"\n  }	100	2025-09-01 11:44:14.824255
6	2999.00	Bluetooth	2025-09-01 11:44:30.991305	https://raw.githubusercontent.com/angeline-31/images/362b160ff70a191e60d303639bb261373a820354/bluetooth2.png	t	Portable Bluetooth speaker with deep bass and 12 hours of playtime.	Bluetooth Speaker	{\n    "Bluetooth Version": "5.0",\n    "Output Power": "20W RMS",\n    "Battery Life": "12 hours continuous playback",\n    "Charging Time": "2.5 hours",\n    "Charging Port": "USB Type-C",\n    "Frequency Response": "70 Hz - 20 kHz",\n    "Water Resistance": "IPX7 waterproof",\n    "Wireless Range": "10 meters",\n    "Weight": "450 g",\n    "Dimensions": "180 x 70 x 70 mm",\n    "Color": "Black",\n    "Controls": "Buttons for volume, track, power, and pairing",\n    "Built-in Microphone": "Yes, for hands-free calls",\n    "Additional Features": "Stereo pairing support, deep bass driver"\n  }	100	2025-09-01 11:44:30.991305
\.


--
-- Data for Name: vas_catalog; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.vas_catalog (service_id, billing_cycle, created_at, features, is_active, price, service_description, service_name, service_type, updated_at) FROM stdin;
9	MONTHLY	2025-09-01 13:08:10.195512	{"data":"100GB","validity":"30 days","speed":"200Mbps","autoExpiry":true,"router":"Included","support":"24x7","noDailyLimit":true}	t	999.00	High-speed WiFi 100GB per month with included router.	WiFi 100GB High-Speed	WiFi	2025-09-01 13:08:10.195512
10	QUARTERLY	2025-09-01 13:08:10.203691	{"data":"200GB","validity":"90 days","speed":"250Mbps","autoExpiry":true,"router":"Included","support":"24x7","noDailyLimit":true}	t	2499.00	High-speed WiFi 200GB per quarter with included router.	WiFi 200GB High-Speed	WiFi	2025-09-01 13:08:10.203691
11	MONTHLY	2025-09-01 13:08:10.212879	{"data":"Unlimited","validity":"30 days","speed":"300Mbps","autoExpiry":true,"router":"Included","support":"24x7","noDailyLimit":true}	t	3999.00	Unlimited high-speed WiFi with included router.	WiFi Unlimited High-Speed	WiFi	2025-09-01 13:08:10.212879
12	QUARTERLY	2025-09-01 13:08:10.22329	{"data":"1TB","validity":"90 days","speed":"300Mbps","autoExpiry":true,"router":"Included","support":"24x7","noDailyLimit":true}	t	4999.00	High-speed WiFi 1TB per quarter with included router.	WiFi 1TB High-Speed	WiFi	2025-09-01 13:08:10.22329
13	YEARLY	2025-09-01 13:08:10.23171	{"data":"Unlimited","validity":"365 days","speed":"500Mbps","autoExpiry":true,"router":"Included","support":"24x7","noDailyLimit":true}	t	11999.00	Unlimited high-speed WiFi yearly with included router.	WiFi Unlimited Yearly	WiFi	2025-09-01 13:08:10.23171
14	MONTHLY	2025-09-01 14:07:20.578287	{"data":"1GB","validity":"30 days","speed":"50Mbps","autoExpiry":true,"dailyLimit":"None","postFUP":"10Mbps","support":"24x7"}	t	199.00	Daily 1GB data with unlimited calls for everyday use.	Daily 1GB Data + Unlimited Calls	Data	2025-09-01 14:07:20.578287
15	QUARTERLY	2025-09-01 14:07:20.588196	{"data":"20GB","validity":"90 days","speed":"100Mbps","autoExpiry":true,"dailyLimit":"None","postFUP":"20Mbps","support":"24x7"}	t	499.00	Weekly 20GB data pack with unlimited calls.	Weekly 50GB Data + Unlimited Calls	Data	2025-09-01 14:07:20.588196
16	MONTHLY	2025-09-01 14:07:20.595081	{"data":"100GB","validity":"30 days","speed":"150Mbps","autoExpiry":true,"dailyLimit":"None","postFUP":"50Mbps","support":"24x7"}	t	999.00	Monthly 100GB data pack with unlimited calls.	Monthly 100GB Data + Unlimited Calls	Data	2025-09-01 14:07:20.595081
17	MONTHLY	2025-09-01 14:07:20.604648	{"data":"Unlimited","validity":"30 days","speed":"150Mbps","autoExpiry":true,"dailyLimit":"None","postFUP":"100Mbps","support":"24x7"}	t	1499.00	Unlimited data with unlimited calls.	Unlimited Data + Calls	Data	2025-09-01 14:07:20.604648
18	YEARLY	2025-09-01 14:07:21.426378	{"data":"2TB","validity":"365 days","speed":"200Mbps","autoExpiry":true,"dailyLimit":"None","postFUP":"100Mbps","support":"24x7"}	t	14999.00	Yearly 2TB data with unlimited calls.	Yearly 2TB Data + Unlimited Calls	Data	2025-09-01 14:07:21.426378
\.


--
-- Name: products_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_product_id_seq', 6, true);


--
-- Name: vas_catalog_service_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.vas_catalog_service_id_seq', 19, true);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (product_id);


--
-- Name: vas_catalog vas_catalog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vas_catalog
    ADD CONSTRAINT vas_catalog_pkey PRIMARY KEY (service_id);


--
-- PostgreSQL database dump complete
--

