--
-- PostgreSQL database dump
--

-- Dumped from database version 15.13
-- Dumped by pg_dump version 15.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    notification_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    is_read boolean NOT NULL,
    message text,
    read_at timestamp(6) without time zone,
    title character varying(255),
    type character varying(255),
    user_id bigint,
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['ORDER'::character varying, 'SUBSCRIPTION'::character varying, 'ORDER_CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- Name: notifications_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications ALTER COLUMN notification_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: notifications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notifications (notification_id, created_at, is_read, message, read_at, title, type, user_id) FROM stdin;
1	2025-09-01 15:13:31.555666	f	Your order with 2 items (Total: ₹4498) has been placed successfully.	\N	Order Placed Successfully	ORDER	1
2	2025-09-01 15:13:47.374664	f	Your order #9 has been cancelled successfully.	\N	Order Cancelled Successfully	ORDER_CANCELLED	1
3	2025-09-01 15:14:18.118984	f	Your subscription for Weekly 50GB Data + Unlimited Calls has been activated successfully.	\N	Subscription Activated	SUBSCRIPTION	1
4	2025-09-01 15:24:55.871684	f	Your subscription for Daily 1GB Data + Unlimited Calls has been renewed successfully.	\N	Subscription Renewed	SUBSCRIPTION	1
5	2025-09-01 15:25:53.025377	f	Your subscription for WiFi 1TB High-Speed has been renewed successfully.	\N	Subscription Renewed	SUBSCRIPTION	1
6	2025-09-01 15:32:49.676954	f	Your subscription for Daily 1GB Data + Unlimited Calls has been activated successfully.	\N	Subscription Activated	SUBSCRIPTION	1
7	2025-09-01 15:33:11.712461	f	Your subscription for WiFi 1TB High-Speed has been renewed successfully.	\N	Subscription Renewed	SUBSCRIPTION	1
8	2025-09-01 15:33:55.125756	f	Your order with 1 items (Total: ₹4998) has been placed successfully.	\N	Order Placed Successfully	ORDER	1
9	2025-09-01 15:34:12.62114	f	Your order #10 has been cancelled successfully.	\N	Order Cancelled Successfully	ORDER_CANCELLED	1
10	2025-09-01 15:36:28.9725	f	Your subscription for Daily 1GB Data + Unlimited Calls has been activated successfully.	\N	Subscription Activated	SUBSCRIPTION	1
11	2025-09-01 15:37:52.158832	f	Your subscription for Daily 1GB Data + Unlimited Calls has been activated successfully.	\N	Subscription Activated	SUBSCRIPTION	1
12	2025-09-01 15:37:52.158832	f	Your subscription for Daily 1GB Data + Unlimited Calls has been activated successfully.	\N	Subscription Activated	SUBSCRIPTION	1
13	2025-09-01 15:39:26.27343	f	Your subscription for Daily 1GB Data + Unlimited Calls has been activated successfully.	\N	Subscription Activated	SUBSCRIPTION	1
14	2025-09-01 15:41:22.805269	f	Your subscription for Daily 1GB Data + Unlimited Calls has been activated successfully.	\N	Subscription Activated	SUBSCRIPTION	1
15	2025-09-01 16:22:17.39316	f	Your subscription for Weekly 50GB Data + Unlimited Calls has been activated successfully.	\N	Subscription Activated	SUBSCRIPTION	1
16	2025-09-01 16:25:20.802166	f	Your order with 2 items (Total: ₹7496) has been placed successfully.	\N	Order Placed Successfully	ORDER	1
17	2025-09-01 16:26:18.356289	f	Your order #11 has been cancelled successfully.	\N	Order Cancelled Successfully	ORDER_CANCELLED	1
18	2025-09-02 09:29:13.703763	f	Your subscription for WiFi Unlimited Yearly has been activated successfully.	\N	Subscription Activated	SUBSCRIPTION	1
19	2025-09-02 09:30:00.883417	f	Your order with 1 items (Total: ₹2499) has been placed successfully.	\N	Order Placed Successfully	ORDER	1
20	2025-09-02 11:34:36.028626	f	Your subscription for WiFi 200GB High-Speed has been activated successfully.	\N	Subscription Activated	SUBSCRIPTION	1
21	2025-09-02 11:35:14.298774	f	Your subscription for Daily 1GB Data + Unlimited Calls has been renewed successfully.	\N	Subscription Renewed	SUBSCRIPTION	1
22	2025-09-02 11:36:40.891473	f	Your order with 2 items (Total: ₹20497) has been placed successfully.	\N	Order Placed Successfully	ORDER	1
23	2025-09-02 11:38:04.346467	f	Your order #13 has been cancelled successfully.	\N	Order Cancelled Successfully	ORDER_CANCELLED	1
24	2025-09-02 16:32:24.170515	f	Your order #12 has been cancelled successfully.	\N	Order Cancelled Successfully	ORDER_CANCELLED	1
25	2025-09-02 16:35:27.634707	f	Your subscription for Weekly 50GB Data + Unlimited Calls has been activated successfully.	\N	Subscription Activated	SUBSCRIPTION	12
26	2025-09-02 16:35:55.885395	f	Your order with 1 items (Total: ₹1499) has been placed successfully.	\N	Order Placed Successfully	ORDER	12
27	2025-09-02 16:36:08.705043	f	Your order #14 has been cancelled successfully.	\N	Order Cancelled Successfully	ORDER_CANCELLED	12
28	2025-09-02 16:39:54.040621	f	Your subscription for Weekly 50GB Data + Unlimited Calls has been activated successfully.	\N	Subscription Activated	SUBSCRIPTION	12
29	2025-09-02 17:21:09.381528	f	Your order with 2 items (Total: ₹3998) has been placed successfully.	\N	Order Placed Successfully	ORDER	1
30	2025-09-02 17:22:25.110751	f	Your order with 1 items (Total: ₹1499) has been placed successfully.	\N	Order Placed Successfully	ORDER	1
31	2025-09-02 17:22:47.425562	f	Your order #16 has been cancelled successfully.	\N	Order Cancelled Successfully	ORDER_CANCELLED	1
32	2025-09-02 17:29:05.294816	f	Your order with 1 items (Total: ₹4497) has been placed successfully.	\N	Order Placed Successfully	ORDER	12
33	2025-09-02 17:29:30.039516	f	Your order #17 has been cancelled successfully.	\N	Order Cancelled Successfully	ORDER_CANCELLED	12
34	2025-09-03 12:32:47.438265	f	Your order with 1 items (Total: ₹4999) has been placed successfully.	\N	Order Placed Successfully	ORDER	1
35	2025-09-03 12:33:04.394113	f	Your order #18 has been cancelled successfully.	\N	Order Cancelled Successfully	ORDER_CANCELLED	1
\.


--
-- Name: notifications_notification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notifications_notification_id_seq', 35, true);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (notification_id);


--
-- PostgreSQL database dump complete
--

