--
-- PostgreSQL database dump
--

-- Dumped from database version 15.13
-- Dumped by pg_dump version 15.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: order_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_items (
    order_item_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer NOT NULL,
    total_price double precision NOT NULL,
    unit_price double precision NOT NULL,
    order_id integer NOT NULL
);


ALTER TABLE public.order_items OWNER TO postgres;

--
-- Name: order_items_order_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.order_items ALTER COLUMN order_item_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_items_order_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders (
    order_id integer NOT NULL,
    discount_amount double precision,
    final_amount double precision NOT NULL,
    order_time timestamp(6) without time zone NOT NULL,
    shipping_address text,
    status character varying(255) NOT NULL,
    total_amount double precision NOT NULL,
    user_id integer NOT NULL,
    cancel_reason text,
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.orders OWNER TO postgres;

--
-- Name: orders_order_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders ALTER COLUMN order_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: order_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.order_items (order_item_id, product_id, quantity, total_price, unit_price, order_id) FROM stdin;
1	1	2	1000	500	1
2	2	1	500	500	1
3	3	1	8999	8999	2
4	2	1	2499	2499	2
5	1	1	1499	1499	3
6	4	2	9998	4999	4
7	5	1	1999	1999	5
8	3	1	8999	8999	6
9	3	1	8999	8999	7
10	2	1	2499	2499	7
11	6	1	2999	2999	8
12	6	1	2999	2999	9
13	1	1	1499	1499	9
14	2	2	4998	2499	10
15	6	1	2999	2999	11
16	1	3	4497	1499	11
17	2	1	2499	2499	12
18	2	1	2499	2499	13
19	3	2	17998	8999	13
20	1	1	1499	1499	14
21	1	1	1499	1499	15
22	2	1	2499	2499	15
23	1	1	1499	1499	16
24	1	3	4497	1499	17
25	4	1	4999	4999	18
\.


--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders (order_id, discount_amount, final_amount, order_time, shipping_address, status, total_amount, user_id, cancel_reason) FROM stdin;
1	0	1300	2025-09-01 18:00:00	\N	CANCELLED	1500	1	\N
2	0	11498	2025-09-01 12:39:42.337	\N	CANCELLED	11498	1	\N
4	0	9998	2025-09-01 14:32:33.947	\N	CANCELLED	9998	1	\N
6	0	8999	2025-09-01 14:38:15.68	\N	CANCELLED	8999	1	\N
7	0	11498	2025-09-01 14:58:01.428	\N	CANCELLED	11498	1	\N
5	0	1999	2025-09-01 14:35:45.12	\N	CANCELLED	1999	1	\N
3	0	1499	2025-09-01 14:14:16.16	\N	CANCELLED	1499	1	\N
8	0	2999	2025-09-01 15:00:32.447	\N	CANCELLED	2999	1	\N
9	0	4498	2025-09-01 15:13:31.511	\N	CANCELLED	4498	1	\N
10	0	4998	2025-09-01 15:33:55.097	\N	CANCELLED	4998	1	\N
11	0	7496	2025-09-01 16:25:20.761	\N	CANCELLED	7496	1	\N
13	0	20497	2025-09-02 11:36:40.851	\N	CANCELLED	20497	1	\N
12	0	2499	2025-09-02 09:30:00.699	\N	CANCELLED	2499	1	Delivery time is too long
14	0	1499	2025-09-02 16:35:55.828	\N	CANCELLED	1499	12	Other
15	0	3998	2025-09-02 17:21:09.358	\N	PROCESSING	3998	1	\N
16	0	1499	2025-09-02 17:22:25.085	\N	CANCELLED	1499	1	Changed my mind
17	0	4497	2025-09-02 17:29:05.274	\N	CANCELLED	4497	12	Ordered by mistake
18	0	4999	2025-09-03 12:32:47.057	\N	CANCELLED	4999	1	Ordered by mistake
\.


--
-- Name: order_items_order_item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.order_items_order_item_id_seq', 25, true);


--
-- Name: orders_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_order_id_seq', 18, true);


--
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (order_item_id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (order_id);


--
-- Name: order_items fkbioxgbv59vetrxe0ejfubep1w; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES public.orders(order_id);


--
-- PostgreSQL database dump complete
--

