--
-- PostgreSQL database dump
--

-- Dumped from database version 15.13
-- Dumped by pg_dump version 15.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: subscriptions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.subscriptions (
    subscription_id bigint NOT NULL,
    auto_renew boolean,
    billing_cycle character varying(255),
    created_at date,
    end_date date,
    next_billing_date date,
    price double precision,
    service_id bigint,
    start_date date,
    status character varying(255),
    target_phone_number character varying(255),
    user_id bigint,
    CONSTRAINT subscriptions_billing_cycle_check CHECK (((billing_cycle)::text = ANY ((ARRAY['MONTHLY'::character varying, 'QUARTERLY'::character varying, 'YEARLY'::character varying])::text[]))),
    CONSTRAINT subscriptions_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);


ALTER TABLE public.subscriptions OWNER TO postgres;

--
-- Name: subscriptions_subscription_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.subscriptions ALTER COLUMN subscription_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscriptions_subscription_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: subscriptions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.subscriptions (subscription_id, auto_renew, billing_cycle, created_at, end_date, next_billing_date, price, service_id, start_date, status, target_phone_number, user_id) FROM stdin;
1	t	MONTHLY	2025-08-29	2025-09-28	2025-09-29	99	5	2025-08-29	ACTIVE	+919876543210	\N
4	t	MONTHLY	2025-09-01	2025-10-01	2025-10-01	1499	17	2025-09-01	ACTIVE	6546545465	1
5	t	QUARTERLY	2025-09-01	2025-11-30	2025-12-01	499	15	2025-09-01	ACTIVE	5445455445	1
6	t	MONTHLY	2025-09-01	2025-10-01	2025-10-01	199	14	2025-09-01	ACTIVE	7998845665	1
7	t	MONTHLY	2025-09-01	2025-10-01	2025-10-01	199	14	2025-09-01	ACTIVE	7998845665	1
8	t	MONTHLY	2025-09-01	2025-10-01	2025-10-01	199	14	2025-09-01	ACTIVE	7998845665	1
9	t	MONTHLY	2025-09-01	2025-10-01	2025-10-01	199	14	2025-09-01	ACTIVE	7998845665	1
10	t	MONTHLY	2025-09-01	2025-10-01	2025-10-01	199	14	2025-09-01	ACTIVE	7998845665	1
11	t	MONTHLY	2025-09-01	2025-10-01	2025-10-01	199	14	2025-09-01	ACTIVE	7998845665	1
12	t	QUARTERLY	2025-09-01	2025-11-30	2025-12-01	499	15	2025-09-01	ACTIVE	9854665564	1
13	t	YEARLY	2025-09-02	2026-09-02	2026-09-02	11999	13	2025-09-02	ACTIVE	9879879879	1
14	t	QUARTERLY	2025-09-02	2025-12-01	2025-12-02	2499	10	2025-09-02	ACTIVE	5842658412	1
2	t	MONTHLY	2024-07-01	2025-10-02	2024-08-02	199	14	2025-09-02	ACTIVE	7987879879	1
15	t	QUARTERLY	2025-09-02	2025-12-01	2025-12-02	499	15	2025-09-02	ACTIVE	9879879879	12
16	t	QUARTERLY	2025-09-02	2025-12-01	2025-12-02	499	15	2025-09-02	ACTIVE	7349570773	12
17	t	QUARTERLY	2025-09-02	2025-12-01	2025-12-02	499	15	2025-09-02	ACTIVE	9879879878	1
18	t	QUARTERLY	2025-09-02	2025-12-01	2025-12-02	499	15	2025-09-02	ACTIVE	7349570773	1
19	t	MONTHLY	2025-09-02	2025-10-02	2025-10-02	199	14	2025-09-02	ACTIVE	9879879879	1
20	t	YEARLY	2025-09-02	2026-09-02	2026-09-02	11999	13	2025-09-02	ACTIVE	9879879879	12
21	t	MONTHLY	2025-09-03	2025-10-03	2025-10-03	199	14	2025-09-03	ACTIVE	9879879879	12
22	t	QUARTERLY	2025-09-03	2025-12-02	2025-12-03	4999	12	2025-09-03	ACTIVE	8248849875	1
3	t	QUARTERLY	2024-04-01	2025-12-02	2024-07-01	4999	12	2025-09-03	ACTIVE	9879879879	1
\.


--
-- Name: subscriptions_subscription_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.subscriptions_subscription_id_seq', 22, true);


--
-- Name: subscriptions subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_pkey PRIMARY KEY (subscription_id);


--
-- PostgreSQL database dump complete
--

